### ISSUE TITLE
Incorrect image name in has_one

### ISSUE THREAD

**Issue by tardinha** [xini/silverstripe-social-share#1]
The has_one image has an incomplete name versus the upload field

https://github.com/xini/silverstripe-social-share/blob/master/code/extensions/SocialShareConfigExtension.php#L19

https://github.com/xini/silverstripe-social-share/blob/master/code/extensions/SocialShareConfigExtension.php#L67

**Comment by xini** [comment]
sorry mate, fixed in 1.0.1
