### ISSUE TITLE
Share on LinkedIn not working

### ISSUE THREAD

**Issue by Thiyagarajantender** [xini/silverstripe-social-share#2]
Share on LinkedIn not working.

Please advise to solve the issue.

Thanks.

**Comment by xini** [comment]
Which sharing option have you set in Site Config? 'Normal links (no Javascript needed)', 'Native sharing buttons (uses Javascript)' or 'AddThis (uses Javascript)'?

**Comment by xini** [comment]
I had a quick look at the module and fixed some smaller things. can you check whether release 3.0.4 fixes your issue? Thanks

**Comment by xini** [comment]
solved in https://github.com/xini/silverstripe-social-share/commit/3bd5a47248df9531e6dcf6097d2523c5d0f334a1
